In [3]:
from binance.cm_futures import CMFutures
from binance.um_futures import UMFutures
from binance.spot import Spot
from pandas import DataFrame
import pandas as pd

In [4]:
um_futures_client = UMFutures()

In [5]:
um_futures_prices = um_futures_client.ticker_price()
um_futures_prices_df = DataFrame(um_futures_prices)
um_futures_prices_df

             symbol      price           time
0          AAVEUSDT    328.080  1735568468682
1    1000CHEEMSUSDT  0.0009193  1735568468238
2        BTCDOMUSDT     3119.0  1735568460319
3         TOKENUSDT  0.0620300  1735568467218
4           BELUSDT    0.57110  1735568470743
..              ...        ...            ...
391         SNTUSDT  0.0366600  1715590784992
392        DOGEUSDT   0.314650  1735568467610
393         BCHUSDC     439.00  1735568466990
394       METISUSDT    42.9000  1735568465229
395         ONEUSDT    0.02716  1735568467206

[396 rows x 3 columns]

In [9]:
import pandas as pd

symbols = ['SUIUSDT',
           'ADAUSDT',
           'DOGEUSDT',
           'SOLUSDT',
           'BNBUSDT',
           'XRPUSDT',
           'ETHUSDT',
           'BTCUSDT']
# empty DataFrame with columns symbol and fr
df_fr = pd.DataFrame(columns=['symbol', 'fr', 'datetime'])


for symbol in symbols:
    um_futures_fr = um_futures_client.funding_rate(symbol, limit=5)
    fr_df = DataFrame(um_futures_fr)

    # change the funding rate to number
    fr_df['fundingRate'] = fr_df['fundingRate'].astype(float)

    # fr_df['fundingTime'] = fr_df['fundingTime'].astype(int)

    fr_df['fr'] = fr_df['fundingRate']*100*365*3
    fr_df['datetime'] = pd.to_datetime(fr_df['fundingTime']/1000, unit='s')

    # get columns symbol and fr
    fr_df = fr_df[['symbol', 'fr', 'datetime']]
    # add rows to the empty DataFrame
    df_fr = pd.concat([fr_df, df_fr])
    print(df_fr)

# drop index
df_fr['datetime'] = df_fr['datetime'].dt.strftime('%Y-%m-%d %H:%M')
df_fr = df_fr.reset_index(drop=True)
print(df_fr)

/var/folders/5y/t5w21c695232j0yt3hlpscpm0000gn/T/ipykernel_41091/923861553.py:30: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fr = pd.concat([fr_df, df_fr])

    symbol         fr                      datetime
0  SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1  SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2  SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3  SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4  SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
    symbol         fr                      datetime
0  ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1  ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2  ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3  ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4  ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0  SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1  SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2  SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3  SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4  SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0   SOLUSDT   0.851910 2024-12-29 00:00:00.000000000
1   SOLUSDT  -2.986065 2024-12-29 08:00:00.000000000
2   SOLUSDT   6.723300 2024-12-29 16:00:00.000000000
3   SOLUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0   BNBUSDT   0.000000 2024-12-29 00:00:00.000000000
1   BNBUSDT   0.000000 2024-12-29 08:00:00.000000000
2   BNBUSDT   0.000000 2024-12-29 16:00:00.000000000
3   BNBUSDT   0.000000 2024-12-30 00:00:00.000000000
4   BNBUSDT  -8.498295 2024-12-30 08:00:00.000999928
0   SOLUSDT   0.851910 2024-12-29 00:00:00.000000000
1   SOLUSDT  -2.986065 2024-12-29 08:00:00.000000000
2   SOLUSDT   6.723300 2024-12-29 16:00:00.000000000
3   SOLUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0   XRPUSDT  10.950000 2024-12-29 00:00:00.000000000
1   XRPUSDT  10.950000 2024-12-29 08:00:00.000000000
2   XRPUSDT   9.929460 2024-12-29 16:00:00.000000000
3   XRPUSDT  -0.877095 2024-12-30 00:00:00.000000000
4   XRPUSDT   0.166440 2024-12-30 08:00:00.000999928
0   BNBUSDT   0.000000 2024-12-29 00:00:00.000000000
1   BNBUSDT   0.000000 2024-12-29 08:00:00.000000000
2   BNBUSDT   0.000000 2024-12-29 16:00:00.000000000
3   BNBUSDT   0.000000 2024-12-30 00:00:00.000000000
4   BNBUSDT  -8.498295 2024-12-30 08:00:00.000999928
0   SOLUSDT   0.851910 2024-12-29 00:00:00.000000000
1   SOLUSDT  -2.986065 2024-12-29 08:00:00.000000000
2   SOLUSDT   6.723300 2024-12-29 16:00:00.000000000
3   SOLUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0   ETHUSDT   6.505395 2024-12-29 00:00:00.000000000
1   ETHUSDT   5.634870 2024-12-29 08:00:00.000000000
2   ETHUSDT  10.386075 2024-12-29 16:00:00.000000000
3   ETHUSDT  10.950000 2024-12-30 00:00:00.000000000
4   ETHUSDT  10.950000 2024-12-30 08:00:00.000999928
0   XRPUSDT  10.950000 2024-12-29 00:00:00.000000000
1   XRPUSDT  10.950000 2024-12-29 08:00:00.000000000
2   XRPUSDT   9.929460 2024-12-29 16:00:00.000000000
3   XRPUSDT  -0.877095 2024-12-30 00:00:00.000000000
4   XRPUSDT   0.166440 2024-12-30 08:00:00.000999928
0   BNBUSDT   0.000000 2024-12-29 00:00:00.000000000
1   BNBUSDT   0.000000 2024-12-29 08:00:00.000000000
2   BNBUSDT   0.000000 2024-12-29 16:00:00.000000000
3   BNBUSDT   0.000000 2024-12-30 00:00:00.000000000
4   BNBUSDT  -8.498295 2024-12-30 08:00:00.000999928
0   SOLUSDT   0.851910 2024-12-29 00:00:00.000000000
1   SOLUSDT  -2.986065 2024-12-29 08:00:00.000000000
2   SOLUSDT   6.723300 2024-12-29 16:00:00.000000000
3   SOLUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
     symbol         fr                      datetime
0   BTCUSDT   8.774235 2024-12-29 00:00:00.000000000
1   BTCUSDT  10.950000 2024-12-29 08:00:00.000000000
2   BTCUSDT  10.950000 2024-12-29 16:00:00.000000000
3   BTCUSDT  -0.045990 2024-12-30 00:00:00.000000000
4   BTCUSDT   9.626145 2024-12-30 08:00:00.000999928
0   ETHUSDT   6.505395 2024-12-29 00:00:00.000000000
1   ETHUSDT   5.634870 2024-12-29 08:00:00.000000000
2   ETHUSDT  10.386075 2024-12-29 16:00:00.000000000
3   ETHUSDT  10.950000 2024-12-30 00:00:00.000000000
4   ETHUSDT  10.950000 2024-12-30 08:00:00.000999928
0   XRPUSDT  10.950000 2024-12-29 00:00:00.000000000
1   XRPUSDT  10.950000 2024-12-29 08:00:00.000000000
2   XRPUSDT   9.929460 2024-12-29 16:00:00.000000000
3   XRPUSDT  -0.877095 2024-12-30 00:00:00.000000000
4   XRPUSDT   0.166440 2024-12-30 08:00:00.000999928
0   BNBUSDT   0.000000 2024-12-29 00:00:00.000000000
1   BNBUSDT   0.000000 2024-12-29 08:00:00.000000000
2   BNBUSDT   0.000000 2024-12-29 16:00:00.000000000
3   BNBUSDT   0.000000 2024-12-30 00:00:00.000000000
4   BNBUSDT  -8.498295 2024-12-30 08:00:00.000999928
0   SOLUSDT   0.851910 2024-12-29 00:00:00.000000000
1   SOLUSDT  -2.986065 2024-12-29 08:00:00.000000000
2   SOLUSDT   6.723300 2024-12-29 16:00:00.000000000
3   SOLUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
0  DOGEUSDT  10.950000 2024-12-29 00:00:00.000000000
1  DOGEUSDT  10.950000 2024-12-29 08:00:00.000000000
2  DOGEUSDT  10.441920 2024-12-29 16:00:00.000000000
3  DOGEUSDT   2.368485 2024-12-30 00:00:00.000000000
4  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
0   ADAUSDT  10.950000 2024-12-29 00:00:00.000000000
1   ADAUSDT  10.950000 2024-12-29 08:00:00.000000000
2   ADAUSDT  10.950000 2024-12-29 16:00:00.000000000
3   ADAUSDT   2.077215 2024-12-30 00:00:00.000000000
4   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
0   SUIUSDT  -4.650465 2024-12-29 00:00:00.000000000
1   SUIUSDT  10.080570 2024-12-29 08:00:00.000000000
2   SUIUSDT  10.950000 2024-12-29 16:00:00.000000000
3   SUIUSDT  10.950000 2024-12-30 00:00:00.000000000
4   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928
      symbol         fr          datetime
0    BTCUSDT   8.774235  2024-12-29 00:00
1    BTCUSDT  10.950000  2024-12-29 08:00
2    BTCUSDT  10.950000  2024-12-29 16:00
3    BTCUSDT  -0.045990  2024-12-30 00:00
4    BTCUSDT   9.626145  2024-12-30 08:00
5    ETHUSDT   6.505395  2024-12-29 00:00
6    ETHUSDT   5.634870  2024-12-29 08:00
7    ETHUSDT  10.386075  2024-12-29 16:00
8    ETHUSDT  10.950000  2024-12-30 00:00
9    ETHUSDT  10.950000  2024-12-30 08:00
10   XRPUSDT  10.950000  2024-12-29 00:00
11   XRPUSDT  10.950000  2024-12-29 08:00
12   XRPUSDT   9.929460  2024-12-29 16:00
13   XRPUSDT  -0.877095  2024-12-30 00:00
14   XRPUSDT   0.166440  2024-12-30 08:00
15   BNBUSDT   0.000000  2024-12-29 00:00
16   BNBUSDT   0.000000  2024-12-29 08:00
17   BNBUSDT   0.000000  2024-12-29 16:00
18   BNBUSDT   0.000000  2024-12-30 00:00
19   BNBUSDT  -8.498295  2024-12-30 08:00
20   SOLUSDT   0.851910  2024-12-29 00:00
21   SOLUSDT  -2.986065  2024-12-29 08:00
22   SOLUSDT   6.723300  2024-12-29 16:00
23   SOLUSDT  10.950000  2024-12-30 00:00
24   SOLUSDT   5.212200  2024-12-30 08:00
25  DOGEUSDT  10.950000  2024-12-29 00:00
26  DOGEUSDT  10.950000  2024-12-29 08:00
27  DOGEUSDT  10.441920  2024-12-29 16:00
28  DOGEUSDT   2.368485  2024-12-30 00:00
29  DOGEUSDT   6.288585  2024-12-30 08:00
30   ADAUSDT  10.950000  2024-12-29 00:00
31   ADAUSDT  10.950000  2024-12-29 08:00
32   ADAUSDT  10.950000  2024-12-29 16:00
33   ADAUSDT   2.077215  2024-12-30 00:00
34   ADAUSDT   8.511435  2024-12-30 08:00
35   SUIUSDT  -4.650465  2024-12-29 00:00
36   SUIUSDT  10.080570  2024-12-29 08:00
37   SUIUSDT  10.950000  2024-12-29 16:00
38   SUIUSDT  10.950000  2024-12-30 00:00
39   SUIUSDT   6.025785  2024-12-30 08:00

In [7]:
from fr import fr

fr.latest_funding_rate()

/Users/sandermets/Projects/hobby/etrade/pstats/app/fr/fr.py:31: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_fr = pd.concat([fr_df, df_fr])

     symbol         fr                      datetime
0   BTCUSDT   9.626145 2024-12-30 08:00:00.000999928
1   ETHUSDT  10.950000 2024-12-30 08:00:00.000999928
2   XRPUSDT   0.166440 2024-12-30 08:00:00.000999928
3   BNBUSDT  -8.498295 2024-12-30 08:00:00.000999928
4   SOLUSDT   5.212200 2024-12-30 08:00:00.000999928
5  DOGEUSDT   6.288585 2024-12-30 08:00:00.000999928
6   ADAUSDT   8.511435 2024-12-30 08:00:00.000999928
7   SUIUSDT   6.025785 2024-12-30 08:00:00.000999928